### ISSUE TITLE
Bug: ZIP file never seems to finish creating itself

### ISSUE THREAD

**Issue by jamescridland** [Simply-Static/simply-static#142] opened 2023-04-25 12:00 UTC
I'm seeing an endless loop in the debug log, reading:

```
[2023-04-25 09:44:46] [class-ss-archive-creation-job.php:125] Current task: create_zip_archive
[2023-04-25 09:44:46] [class-ss-archive-creation-job.php:141] Performing task: create_zip_archive
[2023-04-25 09:44:46] [class-ss-create-zip-archive.php:71] Fetching list of files to include in zip
[2023-04-25 09:44:49] [class-ss-create-zip-archive.php:80] Creating zip archive
[2023-04-25 09:49:28] [class-ss-archive-creation-job.php:125] Current task: create_zip_archive
[2023-04-25 09:49:28] [class-ss-archive-creation-job.php:141] Performing task: create_zip_archive
[2023-04-25 09:49:28] [class-ss-create-zip-archive.php:71] Fetching list of files to include in zip
[2023-04-25 09:49:29] [class-ss-create-zip-archive.php:80] Creating zip archive
[2023-04-25 09:54:58] [class-ss-archive-creation-job.php:125] Current task: create_zip_archive
[2023-04-25 09:54:58] [class-ss-archive-creation-job.php:141] Performing task: create_zip_archive
[2023-04-25 09:54:59] [class-ss-create-zip-archive.php:71] Fetching list of files to include in zip
[2023-04-25 09:55:00] [class-ss-create-zip-archive.php:80] Creating zip archive
[2023-04-25 09:59:27] [class-ss-archive-creation-job.php:125] Current task: create_zip_archive
[2023-04-25 09:59:27] [class-ss-archive-creation-job.php:141] Performing task: create_zip_archive
[2023-04-25 09:59:27] [class-ss-create-zip-archive.php:71] Fetching list of files to include in zip
[2023-04-25 09:59:28] [class-ss-create-zip-archive.php:80] Creating zip archive
[2023-04-25 10:04:42] [class-ss-archive-creation-job.php:125] Current task: create_zip_archive
[2023-04-25 10:04:42] [class-ss-archive-creation-job.php:141] Performing task: create_zip_archive
[2023-04-25 10:04:42] [class-ss-create-zip-archive.php:71] Fetching list of files to include in zip
[2023-04-25 10:04:43] [class-ss-create-zip-archive.php:80] Creating zip archive
```

Looking at the files themselves, it *does* create a ZIP file, but that ZIP file appears to not be valid. I don't see anything in the error log, though; and disappointingly I don't have SSH access to this box so can't go digging further.

My total static-files folder is 3.7GB and contains 40,106 items, so perhaps it's simply run out of memory; but perhaps that need to be caught somewhere?

**Comment by sr293** [comment] 2023-04-27 15:24
Hello @jamescridland. I'm sorry to hear you are experiencing an issue creating a ZIP export of you site. Do you also receive an invalid ZIP file when you create a single post/page export with Simply Static? You can find this option towards the bottom of the sidebar in the WordPress editor under Simply Static.

![image](https://user-images.githubusercontent.com/54094654/234909074-f7d2a9f2-ce1b-44cf-85b3-76bee5f77b63.png)

**Comment by patrickposner** [comment] 2023-05-08 09:13
The problem is that if you need to zip 40k files, Simply Static will most likely time out on a traditional server configuration as we can not run the zip process in batches (like we do with all other export options) and are limited to the max execution time of the server.

While there is no real way to handle that within Simply Static, I recommend using an SSH connection at the end to zip the file with a little batch script instead (which is much faster and does not depend on the web server configuration).

I'm closing this issue now, but we can reopen it if there is further discussion.

**Closed by patrickposner** 2023-05-08 09:13 UTC

**Comment by jamescridland** [comment] 2023-05-08 09:48
Thanks, Patrick. That probably explains the issue I ran into.

The workaround for anyone else is to log into the website's file system and download the files. (I didn't have SSH access).

In the end it was for the best, since I've used the normal Wordpress XML export to give me something I could then import into Hugo - a much better ending, since I'm more in control.
